# We have a conf and classes directory, but we have classes that should
# override those in oe-core, so prepend to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "scarthgap-nodejs-mixin"
BBFILE_PATTERN_scarthgap-nodejs-mixin := "^${LAYERDIR}/"
BBFILE_PRIORITY_scarthgap-nodejs-mixin = "6"

LAYERSERIES_COMPAT_scarthgap-nodejs-mixin = "scarthgap"

LAYERDEPENDS_scarthgap-nodejs-mixin = "core"

NODE_VERSION ?= "22.11.0%"
